name: C/C++ CI

on:
  push:
    branches: 
      - master
      - development
  pull_request:
    branches: 
      - master
      - development
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-latest]
        include:
        - os: ubuntu-latest
          TARGET: armv7-unknown-linux-musleabihf
          COMPILER: arm-linux-gnueabihf-gcc-5
          LINKER: gcc-5-arm-linux-gnueabihf

        - os: ubuntu-latest
          TARGET: x86_64-unknown-linux-musl
          COMPILER: gcc
          LINKER: gcc

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Update apt
      run: sudo apt-get update
    - name: Installing Dependencies  
      run: sudo apt-get install libglew-dev libglfw3-dev>=3.3 libglm-dev -y
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: Test Binary
      timeout-minutes: 1
      run: ./game
#  build-mac:
#    runs-on: macos-latest
#
#    steps:
#    - uses: actions/checkout@v2
#      with:
#        submodules: true
#    - name: Installing Dependencies
#      run: brew install glew glfw glm pkg-config
#    - name: cmake
#      run: cmake .
#    - name: make
#      run: make
#    - name: Test Binary
#      timeout-minutes: 1
#      run: ./game    
      
  build-win:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Adding MSYS2 to path
      run: echo "::add-path::C:\msys64\usr\bin;C:\msys64\usr\local\bin;"
    - name: Installing Dependencies
      shell: cmd
      run: pacman -S mingw-w64-x86_64-glew mingw-w64-x86_64-glfw mingw-w64-x86_64-glm --noconfirm
    - name: cmake
      shell: cmd
      run: C:/msys64/mingw64/bin/cmake.exe -G "MinGW Makefiles" .
    - name: make
      run: make
    - name: Test Binary
      timeout-minutes: 1
      run: ./game.exe